CC=g++
CPPFLAGS=-Wall -g

EXECUTABLES=func_template class_template

build: $(EXECUTABLES)

simple_template: func_template.cpp

class_template: class_template.cpp

clean:
	rm -rf *.o *.so *.a $(EXECUTABLES)
